//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: dta-wed-api/v1/questionnaires/questionnaires.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClient`, then call methods of this protocol to make API calls.
internal protocol Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientInterceptorFactoryProtocol? { get }

  func getQuestionnaireItemsByQuestionnaireId(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdResponse>

  func createQuestionnaireAnswers(
    _ request: Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersRequest, Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersResponse>

  func getQuestionnaireAnswersByUserId(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdResponse>

  func getQuestionnaireAnswersByAnswerId(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdResponse>

  func deleteQuestionnaireAnswersByAnswerId(
    _ request: Dta_Wed_Api_V1_Questionnaires_DeleteQuestionnaireAnswersByAnswerIdRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Dta_Wed_Api_V1_Questionnaires_DeleteQuestionnaireAnswersByAnswerIdRequest, SwiftProtobuf.Google_Protobuf_Empty>
}

extension Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientProtocol {
  internal var serviceName: String {
    return "dta.wed.api.v1.questionnaires.QuestionnairesData"
  }

  /// Unary call to GetQuestionnaireItemsByQuestionnaireId
  ///
  /// - Parameters:
  ///   - request: Request to send to GetQuestionnaireItemsByQuestionnaireId.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getQuestionnaireItemsByQuestionnaireId(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdResponse> {
    return self.makeUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.getQuestionnaireItemsByQuestionnaireId.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetQuestionnaireItemsByQuestionnaireIdInterceptors() ?? []
    )
  }

  /// Unary call to CreateQuestionnaireAnswers
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateQuestionnaireAnswers.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createQuestionnaireAnswers(
    _ request: Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersRequest, Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersResponse> {
    return self.makeUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.createQuestionnaireAnswers.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateQuestionnaireAnswersInterceptors() ?? []
    )
  }

  /// Unary call to GetQuestionnaireAnswersByUserId
  ///
  /// - Parameters:
  ///   - request: Request to send to GetQuestionnaireAnswersByUserId.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getQuestionnaireAnswersByUserId(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdResponse> {
    return self.makeUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.getQuestionnaireAnswersByUserId.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetQuestionnaireAnswersByUserIdInterceptors() ?? []
    )
  }

  /// Unary call to GetQuestionnaireAnswersByAnswerId
  ///
  /// - Parameters:
  ///   - request: Request to send to GetQuestionnaireAnswersByAnswerId.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getQuestionnaireAnswersByAnswerId(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdResponse> {
    return self.makeUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.getQuestionnaireAnswersByAnswerId.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetQuestionnaireAnswersByAnswerIdInterceptors() ?? []
    )
  }

  /// Unary call to DeleteQuestionnaireAnswersByAnswerId
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteQuestionnaireAnswersByAnswerId.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteQuestionnaireAnswersByAnswerId(
    _ request: Dta_Wed_Api_V1_Questionnaires_DeleteQuestionnaireAnswersByAnswerIdRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Dta_Wed_Api_V1_Questionnaires_DeleteQuestionnaireAnswersByAnswerIdRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.deleteQuestionnaireAnswersByAnswerId.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteQuestionnaireAnswersByAnswerIdInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataNIOClient")
internal final class Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClient: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the dta.wed.api.v1.questionnaires.QuestionnairesData service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataNIOClient: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientInterceptorFactoryProtocol?

  /// Creates a client for the dta.wed.api.v1.questionnaires.QuestionnairesData service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientInterceptorFactoryProtocol? { get }

  func makeGetQuestionnaireItemsByQuestionnaireIDCall(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdResponse>

  func makeCreateQuestionnaireAnswersCall(
    _ request: Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersRequest, Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersResponse>

  func makeGetQuestionnaireAnswersByUserIDCall(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdResponse>

  func makeGetQuestionnaireAnswersByAnswerIDCall(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdResponse>

  func makeDeleteQuestionnaireAnswersByAnswerIDCall(
    _ request: Dta_Wed_Api_V1_Questionnaires_DeleteQuestionnaireAnswersByAnswerIdRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Dta_Wed_Api_V1_Questionnaires_DeleteQuestionnaireAnswersByAnswerIdRequest, SwiftProtobuf.Google_Protobuf_Empty>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.serviceDescriptor
  }

  internal var interceptors: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeGetQuestionnaireItemsByQuestionnaireIDCall(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdResponse> {
    return self.makeAsyncUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.getQuestionnaireItemsByQuestionnaireId.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetQuestionnaireItemsByQuestionnaireIdInterceptors() ?? []
    )
  }

  internal func makeCreateQuestionnaireAnswersCall(
    _ request: Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersRequest, Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersResponse> {
    return self.makeAsyncUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.createQuestionnaireAnswers.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateQuestionnaireAnswersInterceptors() ?? []
    )
  }

  internal func makeGetQuestionnaireAnswersByUserIDCall(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdResponse> {
    return self.makeAsyncUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.getQuestionnaireAnswersByUserId.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetQuestionnaireAnswersByUserIdInterceptors() ?? []
    )
  }

  internal func makeGetQuestionnaireAnswersByAnswerIDCall(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdResponse> {
    return self.makeAsyncUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.getQuestionnaireAnswersByAnswerId.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetQuestionnaireAnswersByAnswerIdInterceptors() ?? []
    )
  }

  internal func makeDeleteQuestionnaireAnswersByAnswerIDCall(
    _ request: Dta_Wed_Api_V1_Questionnaires_DeleteQuestionnaireAnswersByAnswerIdRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Dta_Wed_Api_V1_Questionnaires_DeleteQuestionnaireAnswersByAnswerIdRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeAsyncUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.deleteQuestionnaireAnswersByAnswerId.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteQuestionnaireAnswersByAnswerIdInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataAsyncClientProtocol {
  internal func getQuestionnaireItemsByQuestionnaireId(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdResponse {
    return try await self.performAsyncUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.getQuestionnaireItemsByQuestionnaireId.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetQuestionnaireItemsByQuestionnaireIdInterceptors() ?? []
    )
  }

  internal func createQuestionnaireAnswers(
    _ request: Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersResponse {
    return try await self.performAsyncUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.createQuestionnaireAnswers.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateQuestionnaireAnswersInterceptors() ?? []
    )
  }

  internal func getQuestionnaireAnswersByUserId(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdResponse {
    return try await self.performAsyncUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.getQuestionnaireAnswersByUserId.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetQuestionnaireAnswersByUserIdInterceptors() ?? []
    )
  }

  internal func getQuestionnaireAnswersByAnswerId(
    _ request: Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdResponse {
    return try await self.performAsyncUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.getQuestionnaireAnswersByAnswerId.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetQuestionnaireAnswersByAnswerIdInterceptors() ?? []
    )
  }

  internal func deleteQuestionnaireAnswersByAnswerId(
    _ request: Dta_Wed_Api_V1_Questionnaires_DeleteQuestionnaireAnswersByAnswerIdRequest,
    callOptions: CallOptions? = nil
  ) async throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try await self.performAsyncUnaryCall(
      path: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.deleteQuestionnaireAnswersByAnswerId.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteQuestionnaireAnswersByAnswerIdInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataAsyncClient: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

internal protocol Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'getQuestionnaireItemsByQuestionnaireId'.
  func makeGetQuestionnaireItemsByQuestionnaireIdInterceptors() -> [ClientInterceptor<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireItemsByQuestionnaireIdResponse>]

  /// - Returns: Interceptors to use when invoking 'createQuestionnaireAnswers'.
  func makeCreateQuestionnaireAnswersInterceptors() -> [ClientInterceptor<Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersRequest, Dta_Wed_Api_V1_Questionnaires_CreateQuestionnaireAnswersResponse>]

  /// - Returns: Interceptors to use when invoking 'getQuestionnaireAnswersByUserId'.
  func makeGetQuestionnaireAnswersByUserIdInterceptors() -> [ClientInterceptor<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByUserIdResponse>]

  /// - Returns: Interceptors to use when invoking 'getQuestionnaireAnswersByAnswerId'.
  func makeGetQuestionnaireAnswersByAnswerIdInterceptors() -> [ClientInterceptor<Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdRequest, Dta_Wed_Api_V1_Questionnaires_GetQuestionnaireAnswersByAnswerIdResponse>]

  /// - Returns: Interceptors to use when invoking 'deleteQuestionnaireAnswersByAnswerId'.
  func makeDeleteQuestionnaireAnswersByAnswerIdInterceptors() -> [ClientInterceptor<Dta_Wed_Api_V1_Questionnaires_DeleteQuestionnaireAnswersByAnswerIdRequest, SwiftProtobuf.Google_Protobuf_Empty>]
}

internal enum Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "QuestionnairesData",
    fullName: "dta.wed.api.v1.questionnaires.QuestionnairesData",
    methods: [
      Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.getQuestionnaireItemsByQuestionnaireId,
      Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.createQuestionnaireAnswers,
      Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.getQuestionnaireAnswersByUserId,
      Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.getQuestionnaireAnswersByAnswerId,
      Dta_Wed_Api_V1_Questionnaires_QuestionnairesDataClientMetadata.Methods.deleteQuestionnaireAnswersByAnswerId,
    ]
  )

  internal enum Methods {
    internal static let getQuestionnaireItemsByQuestionnaireId = GRPCMethodDescriptor(
      name: "GetQuestionnaireItemsByQuestionnaireId",
      path: "/dta.wed.api.v1.questionnaires.QuestionnairesData/GetQuestionnaireItemsByQuestionnaireId",
      type: GRPCCallType.unary
    )

    internal static let createQuestionnaireAnswers = GRPCMethodDescriptor(
      name: "CreateQuestionnaireAnswers",
      path: "/dta.wed.api.v1.questionnaires.QuestionnairesData/CreateQuestionnaireAnswers",
      type: GRPCCallType.unary
    )

    internal static let getQuestionnaireAnswersByUserId = GRPCMethodDescriptor(
      name: "GetQuestionnaireAnswersByUserId",
      path: "/dta.wed.api.v1.questionnaires.QuestionnairesData/GetQuestionnaireAnswersByUserId",
      type: GRPCCallType.unary
    )

    internal static let getQuestionnaireAnswersByAnswerId = GRPCMethodDescriptor(
      name: "GetQuestionnaireAnswersByAnswerId",
      path: "/dta.wed.api.v1.questionnaires.QuestionnairesData/GetQuestionnaireAnswersByAnswerId",
      type: GRPCCallType.unary
    )

    internal static let deleteQuestionnaireAnswersByAnswerId = GRPCMethodDescriptor(
      name: "DeleteQuestionnaireAnswersByAnswerId",
      path: "/dta.wed.api.v1.questionnaires.QuestionnairesData/DeleteQuestionnaireAnswersByAnswerId",
      type: GRPCCallType.unary
    )
  }
}

